<?php


return [

    "color" => [
        "names" => [
            ["name"=>"Principale",'id'=>"primary"],
            ["name"=>"Successo",'id'=>"success"],
            ["name"=>"Alert",'id'=>"warning"],
            ["name"=>"Errore",'id'=>"danger"],
            ["name"=>"Bianco",'id'=>"white"],
            ["name"=>"Grigio 1",'id'=>"gray-1"],
            ["name"=>"Grigio 2",'id'=>"gray-2"],
            ["name"=>"Grigio 3",'id'=>"gray-3"],
            ["name"=>"Nero",'id'=>"black"],
            ["name"=>"Rosso",'id'=>"red"],
            ["name"=>"Blu",'id'=>"blue"],
            ["name"=>"Verde",'id'=>"green"],
            ["name"=>"Giallo",'id'=>"yellow"],
            ["name"=>"Arancione",'id'=>"orange"],
            ["name"=>"Verde Acqua",'id'=>"teal"],
            ["name"=>"Ciano",'id'=>"cyan"],
            ["name"=>"Rosa",'id'=>"pink"],
            ["name"=>"Badge: sfondo Off",'id'=>"badge-background-off"],
            ["name"=>"Badge: sfondo On",'id'=>"badge-background-on"],
            ["name"=>"Ruolo: sfondo",'id'=>"badge-role-bg-color"],
            ["name"=>"Ruolo: testo",'id'=>"badge-role-text-color"],
            ["name"=>"Menu: sfondo",'id'=>"sidebar-bg"],
            ["name"=>"Menu: attivo",'id'=>"sidebar-nav-link-active-bg"],
            ["name"=>"Menu: icona attiva",'id'=>"sidebar-nav-link-active-icon-color"],
            ["name"=>"Paginazione: hover",'id'=>"pagination-hover-bg"],
            ["name"=>"Bottone: Hover",'id'=>"hover-primary"],
            ["name"=>"Bottone: Shadow",'id'=>"shadow-primary"],
            ["name"=>"Filtro Attivo: hover",'id'=>"filter-active-hover"],
            ["name"=>"Filtro Attivo: sfondo",'id'=>"filter-active-bg"],
            ["name"=>"Filtro Attivo: ombra",'id'=>"filter-active-shadow"],
        ],

        "values" =>[
            ["value"=>"#20405f",'id'=>"primary", "type"=>"color"],
            ["value"=>"#60cf7d",'id'=>"success", "type"=>"color"],
            ["value"=>"#f5e230",'id'=>"warning", "type"=>"color"],
            ["value"=>"#fe3f61",'id'=>"danger", "type"=>"color"],
            ["value"=>"#ffffff",'id'=>"white", "type"=>"color"],
            ["value"=>"#5c6873",'id'=>"gray-1", "type"=>"color"],
            ["value"=>"#8697a7",'id'=>"gray-2", "type"=>"color"],
            ["value"=>"#f3f8ff",'id'=>"gray-3", "type"=>"color"],
            ["value"=>"#000000",'id'=>"black", "type"=>"color"],
            ["value"=>"#60cf7d",'id'=>"green", "type"=>"color"],
            ["value"=>"#4273fa",'id'=>"blue", "type"=>"color"],
            ["value"=>"#fe3f61",'id'=>"red", "type"=>"color"],
            ["value"=>"#ffc107",'id'=>"yellow", "type"=>"color"],
            ["value"=>"#f8cb00",'id'=>"orange", "type"=>"color"],
            ["value"=>"#20405f",'id'=>"teal", "type"=>"color"],
            ["value"=>"#17a2b8",'id'=>"cyan", "type"=>"color"],
            ["value"=>"#e83e8c",'id'=>"pink", "type"=>"color"],
            ["value"=>"#20c997",'id'=>"badge-background-off", "type"=>"status"],
            ["value"=>"#17a2b8",'id'=>"badge-background-on", "type"=>"status"],
            ["value"=>"#F5BE30",'id'=>"badge-role-bg-color", "type"=>"status"],
            ["value"=>"#000000",'id'=>"badge-role-text-color", "type"=>"status"],
            ["value"=>"#485779",'id'=>"sidebar-bg", "type"=>"status"],
            ["value"=>"#4273FA",'id'=>"sidebar-nav-link-active-bg", "type"=>"status"],
            ["value"=>"#FFFFFF",'id'=>"sidebar-nav-link-active-icon-color", "type"=>"status"],
            ["value"=>"#f3f8ff",'id'=>"pagination-hover-bg", "type"=>"status"],
            ["value"=>"#104ef9",'id'=>"hover-primary", "type"=>"status"],
            ["value"=>"#7498fb",'id'=>"shadow-primary", "type"=>"status"],
            ["value"=>"#60CF7D",'id'=>"filter-active-hover", "type"=>"status"],
            ["value"=>"#3ac25e",'id'=>"filter-active-bg", "type"=>"status"],
            ["value"=>"#87db9d",'id'=>"filter-active-shadow", "type"=>"status"],
        ]
    ],


];
